name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build --all --release && strip target/release/kuuubedit && tar -czvf target/release/kuuubedit_${{ github.ref_name }}_linux_x64.tar.gz target/release/kuuubedit

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: target/release/kuuubedit_${{ github.ref_name }}_linux_x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build --all --release && powershell Compress-Archive target/release/kuuubedit.exe target/release/kuuubedit_${{ github.ref_name }}_windows_x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: target/release/kuuubedit_${{ github.ref_name }}_windows_x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
